# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SalesDocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket_number', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('delivery_weight', models.IntegerField()),
                ('percent_moisture', models.DecimalField(decimal_places=1, max_digits=3)),
                ('premium_weight', models.IntegerField()),
                ('commercial_weight', models.IntegerField()),
                ('oil_weight', models.IntegerField()),
                ('net_payment', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Silo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('export', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=20)),
                ('charting_colour', models.CharField(max_length=12)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Weighings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=6)),
                ('silo_emptyed', models.BooleanField()),
                ('weight', models.IntegerField()),
                ('report_date', models.DateTimeField()),
                ('from_silo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='harvest.Silo')),
                ('to_silo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='harvest.Silo')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.Variety')),
            ],
        ),
    ]
