# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weighings',
            name='silo_emptyed',
        ),
        migrations.AlterField(
            model_name='salesdocket',
            name='commercial_weight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesdocket',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesdocket',
            name='oil_weight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesdocket',
            name='premium_weight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='weighings',
            name='operation',
            field=models.CharField(choices=[('dehusk', 'Dehusk'), ('resort', 'Resort'), ('sale', 'Sale')], default='dehusk', max_length=6),
        ),
        migrations.AlterField(
            model_name='weighings',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
