# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0002_auto_20170207_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdocket',
            name='commercial_weight',
        ),
        migrations.RemoveField(
            model_name='salesdocket',
            name='oil_weight',
        ),
        migrations.RemoveField(
            model_name='salesdocket',
            name='premium_weight',
        ),
    ]
