# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0003_auto_20170207_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighings',
            name='silo_emptyed',
            field=models.BooleanField(default=False),
        ),
    ]
