# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0004_weighings_silo_emptyed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighings',
            name='silo_emptyed',
            field=models.IntegerField(default=0),
        ),
    ]
