# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0005_auto_20170209_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silo',
            name='export',
            field=models.IntegerField(default=0),
        ),
    ]
