# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0007_auto_20170209_1256'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salesdocket',
            table=None,
        ),
    ]
