# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0008_auto_20170209_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdocket',
            name='commercial_weight',
        ),
        migrations.RemoveField(
            model_name='salesdocket',
            name='oil_weight',
        ),
        migrations.RemoveField(
            model_name='salesdocket',
            name='premium_weight',
        ),
        migrations.RemoveField(
            model_name='weighings',
            name='silo_emptyed',
        ),
    ]
