# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('harvest', '0009_auto_20170213_1429'),
	]

	operations = [
		migrations.RenameModel('Variety', 'Block'),
		migrations.RenameField('Weighings', 'variety', 'block'),
	]
