# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0010_auto_20170215_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Block', 'verbose_name_plural': 'Blocks'},
        ),
        migrations.RemoveField(
            model_name='block',
            name='block',
        ),
    ]
