# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0011_auto_20170216_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdocket',
            old_name='docket_number',
            new_name='consignment_number',
        ),
        migrations.RenameField(
            model_name='salesdocket',
            old_name='date',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='salesdocket',
            old_name='delivery_weight',
            new_name='kg_weight_received',
        ),
        migrations.RenameField(
            model_name='salesdocket',
            old_name='percent_moisture',
            new_name='moisture_content_pct',
        ),
    ]
