# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0012_auto_20170218_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocket',
            name='ckr_pct_1_year_prev',
            field=models.FloatField(blank=True, default=0.0, help_text='CKR% 1 Yr Prev, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='ckr_pct_2_year_prev',
            field=models.FloatField(blank=True, default=0.0, help_text='CKR% 2 Yr Prev, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='ckr_pct_3_year_prev',
            field=models.FloatField(blank=True, default=0.0, help_text='CKR% 3 Yr Prev, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='ckr_pct_ytd',
            field=models.FloatField(blank=True, default=0.0, help_text='CKR% YTD, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='compulsory_levy',
            field=models.FloatField(blank=True, default=0.0, help_text='Compulsory Levy, Payment Particulars'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='first_payment_value',
            field=models.FloatField(blank=True, default=0.0, help_text='First Payment Value, Payment Particulars'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='foreign_matter_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Foreign_matter%, '),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='heavy_discoloration_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Heavy Discoloration%, Reject Kernel Recovery'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='heavy_germination_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Heavy Germination %, Reject Kernel Recovery'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='heavy_immaturity_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Heavy Immaturity%, Reject Kernel Recovery'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='insect_damage_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Insect Damage%, Reject Kernel Recovery'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='internal_discolouration_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Internal Discolouration%, Reject Kernel Recovery'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='kg_weight10_pct_mc',
            field=models.FloatField(blank=True, default=0.0, help_text='KG-Weight10%M.C., '),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='laboratory_fee',
            field=models.FloatField(blank=True, default=0.0, help_text='Laboratory Fee, Payment Particulars'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='light_discoloration_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Light Discoloration %'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='light_germination_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Light Germination%'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='light_immaturity_kr_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Light Immaturity KR%'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='mic35_pct_mc_commercial_kernel_kg',
            field=models.FloatField(blank=True, default=0.0, help_text='MIC3.5%MC Com.Kernel Kg, Macadamia Industry Calculation'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='mic35_pct_mc_commercial_kernel_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='MIC3.5%MC Com.Kernel %, Macadamia Industry Calculation'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='mic35_pct_mc_levy_per_kg',
            field=models.FloatField(blank=True, default=0.0, help_text='MIC3.5%MC Levy /Kg, Macadamia Industry Calculation'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='mic35_pct_mc_premium_kernel_kg',
            field=models.FloatField(blank=True, default=0.0, help_text='MIC3.5%MC Prem.Kernel Kg, Macadamia Industry Calculation'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='mic35_pct_mc_premium_kernel_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='MIC3.5%MC Prem.Kernel %, Macadamia Industry Calculation'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='mic35_pct_mc_reject_kernel_kg',
            field=models.FloatField(blank=True, default=0.0, help_text='MIC3.5%MC Rej.Kernel Kg, Macadamia Industry Calculation'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='mic35_pct_mc_reject_kernel_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='MIC3.5%MC Rej.Kernel %, Macadamia Industry Calculation'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='mic35_pct_mc_total_kernel_kg',
            field=models.FloatField(blank=True, default=0.0, help_text='MIC3.5%MC Total Kernel Kg, Macadamia Industry Calculation'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='mic35_pct_mc_total_kernel_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='MIC3.5%MC Tot.Kernel %, Macadamia Industry Calculation'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='mic35_pct_mc_total_levy',
            field=models.FloatField(blank=True, default=0.0, help_text='MIC3.5%MC Total Levy, Macadamia Industry Calculation'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='mould_units_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Mould Units%, Reject Kernel Recovery'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='ncv_commercial_nis_per_kg_nis',
            field=models.FloatField(blank=True, default=0.0, help_text='NCV Commercial NIS /Kg NIS, Notional Consignment Value'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='ncv_freight_subsidy_per_kg',
            field=models.FloatField(blank=True, default=0.0, help_text='NCV Freight Subsidy/Kg, Notional Consignment Value'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='ncv_premium_nis_per_kg_nis',
            field=models.FloatField(blank=True, default=0.0, help_text='NCV Premium NIS /Kg NIS, Notional Consignment Value'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='ncv_reject_adjustment_per_kg_nis',
            field=models.FloatField(blank=True, default=0.0, help_text='NCV Reject adjustment /Kg NIS, Notional Consignment Value'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='ncv_total_per_kg_nis',
            field=models.FloatField(blank=True, default=0.0, help_text='NCV Total /Kg NIS, Notional Consignment Value'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='ncv_total_value',
            field=models.FloatField(blank=True, default=0.0, help_text='NCV Total Value, Notional Consignment Value'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='ncv_whole_kernel_adjustmnt_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='NCV Whole Kernel Adjustmnt %, Notional Consignment Value'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='ncv_whole_kernel_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='NCV Whole Kernel %, Notional Consignment Value'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='ni_st_1_year_prev',
            field=models.FloatField(blank=True, default=0.0, help_text='NIS(t) 1 Yr Prev, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='ni_st_2_year_prev',
            field=models.FloatField(blank=True, default=0.0, help_text='NIS(t) 2 Yr Prev, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='ni_st_3_year_prev',
            field=models.FloatField(blank=True, default=0.0, help_text='NIS(t) 3 Yr Prev, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='ni_st_ytd',
            field=models.FloatField(blank=True, default=0.0, help_text='NIS(t) YTD, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='payment_due',
            field=models.FloatField(blank=True, default=0.0, help_text='Payment due, Payment Particulars'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='pkr_pct_1_year_prev',
            field=models.FloatField(blank=True, default=0.0, help_text='PKR% 1 Yr Prev, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='pkr_pct_2_year_prev',
            field=models.FloatField(blank=True, default=0.0, help_text='PKR% 2 Yr Prev, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='pkr_pct_3_year_prev',
            field=models.FloatField(blank=True, default=0.0, help_text='PKR% 3 Yr Prev, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='pkr_pct_ytd',
            field=models.FloatField(blank=True, default=0.0, help_text='PKR% YTD, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='premium_kernel_recovery_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Premium Kernel Recovery %, '),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='reject_penalty_cost_aud',
            field=models.FloatField(blank=True, default=0.0, help_text='Reject Penalty Cost AUD'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='rkr_pct_1_year_prev',
            field=models.FloatField(blank=True, default=0.0, help_text='RKR% 1 Yr Prev, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='rkr_pct_2_year_prev',
            field=models.FloatField(blank=True, default=0.0, help_text='RKR% 2 Yr Prev, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='rkr_pct_3_year_prev',
            field=models.FloatField(blank=True, default=0.0, help_text='RKR% 3 Yr Prev, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='rkr_pct_ytd',
            field=models.FloatField(blank=True, default=0.0, help_text='RKR% YTD, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='shell_units_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Shell Units%'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='total_commercial_kr_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Total Commercial KR%, '),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='total_kernel_recovery_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Total Kernel Recovery%'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='total_pct_leviable_kernel',
            field=models.FloatField(blank=True, default=0.0, help_text='Total% Leviable Kernel, Macadamia Industry Calculation'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='total_reject_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Total Reject%, Reject Kernel Recovery'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='total_units_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Total units=%'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='wk_pct_1_year_prev',
            field=models.FloatField(blank=True, default=0.0, help_text='WK% 1 Yr Prev, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='wk_pct_2_year_prev',
            field=models.FloatField(blank=True, default=0.0, help_text='WK% 2 Yr Prev, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='wk_pct_3_year_prev',
            field=models.FloatField(blank=True, default=0.0, help_text='WK% 3 Yr Prev, YTD & Last 3 Years data'),
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='wk_pct_ytd',
            field=models.FloatField(blank=True, default=0.0, help_text='WK% YTD, YTD & Last 3 Years data'),
        ),
        migrations.AlterField(
            model_name='salesdocket',
            name='kg_weight_received',
            field=models.FloatField(blank=True, default=0.0, help_text='KG-Weight_Received, '),
        ),
        migrations.AlterField(
            model_name='salesdocket',
            name='moisture_content_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='MoistureContent-pct, '),
        ),
    ]
