# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0013_auto_20170218_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weighings',
            options={'verbose_name': 'Weighing', 'verbose_name_plural': 'Weighings'},
        ),
        migrations.AddField(
            model_name='salesdocket',
            name='report_date_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='salesdocket',
            name='net_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
