# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0014_auto_20170224_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdocket',
            name='report_date_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
