# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0015_auto_20170224_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesdocket',
            options={'permissions': (('view_salesdocket_reports', 'View Consignments Report Summaries'), ('download_salesdocket_data', 'Download Consignments CSV data')), 'verbose_name': 'Consignment', 'verbose_name_plural': 'Consignments'},
        ),
        migrations.AlterModelOptions(
            name='weighings',
            options={'permissions': (('view_weighings_reports', 'View Weighing Report Summaries'), ('download_weighings_data', 'Download Weighing CSV data')), 'verbose_name': 'Weighing', 'verbose_name_plural': 'Weighings'},
        ),
        migrations.AlterField(
            model_name='weighings',
            name='from_silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='harvest.Silo'),
        ),
        migrations.AlterField(
            model_name='weighings',
            name='to_silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='harvest.Silo'),
        ),
    ]
