# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0016_auto_20170321_0736'),
    ]

    operations = [
		migrations.RunSQL("UPDATE harvest_weighings SET from_silo_id = null WHERE from_silo_id = 0"),
		migrations.RunSQL("UPDATE harvest_weighings SET to_silo_id = null WHERE to_silo_id = 0")
    ]
