# Generated by Django 2.0.4 on 2018-04-27 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0017_auto_20170321_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='harvest.Farm'),
        ),
        migrations.AlterField(
            model_name='weighings',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='harvest.Block'),
        ),
        migrations.AlterField(
            model_name='weighings',
            name='from_silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='harvest.Silo'),
        ),
        migrations.AlterField(
            model_name='weighings',
            name='to_silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='harvest.Silo'),
        ),
    ]
