# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:12.18
    # network_mode: "host"
    restart: always
    environment:
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: xela
      POSTGRES_USER: alex
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
